Update admin-calendar, google-calendar, calendar, & schedule
ucfai/ucfai.github.io pull request #64
Opened 2024-03-17 04:49 UTC by SrinilaiK

Migrated AI@UCF events from a personal email's calendar to an AI@UCF-specific email's calendar.

2024-03-18 16:25 UTC, jmuchovej requested changes

2024-03-18 16:25 UTC, jmuchovej commented on public/_redirects
> +/admin-calendar  https://calendar.google.com/calendar/u/0?cid=M2E1MDQ3ZjUxNGRlYmY3M2EzM2ZhN2Y3NzM1NGVhZTFlZDlhNGJjZTlmZGNmOTkyOWY2YWE1MzY4ZWQ1MmU5NkBncm91cC5jYWxlbmRhci5nb29nbGUuY29t   301
this looks like it's including google's `/u/N` string. i don't know that this will correctly work. can you remove that part of the string?

2024-03-18 16:25 UTC, jmuchovej commented on public/_redirects
> +/google-calendar https://calendar.google.com/calendar/u/0?cid=NWRjM2Y3NjU0ZjhhY2FhNDJmY2QxYTExZDk2ZWE1YTNhMDFkZDFhZDM0ZTMxNjVlOTJlMDJiZDZlY2E4ZGYwMEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t   301
ditto as above comment.

2025-08-25 23:15 UTC, GauravKano approved these changes
All changes seem to be working and point to the correct google calendar.

2025-08-25 23:25 UTC, merged